# Generated by Django 3.2 on 2021-05-09 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obfuscation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mailid',
            table='mails',
        ),
    ]
